site_name: EnduraNet Documentation
site_url: https://enduranet.edcgaming.org/docs/
use_directory_urls: true # or false, test both if needed

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary:
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.footer
    - toc.integrate
    - content.code.annotate
    - content.image.popup
    - search.suggest
    - search.highlight
    - content.tooltips

markdown_extensions:
  - admonition
  - attr_list # For adding attributes like 'caption' to elements
  - md_in_html # To process Markdown within HTML blocks
  - pymdownx.details # Useful for collapsible admonitions
  - pymdownx.superfences # For nesting code blocks within admonitions
  - tables # For enabling Markdown tables
  - fenced_code # For fenced code blocks (```)
  - footnotes # For using footnotes

nav:
  - Front Page: index.md
  - How to Use:
      - Viewing Data: viewing-data.md
      - Editing Data:
          - Logging In: edit/logging-in.md
          - Adding & Editing Members: edit/edit-members.md
          - Adding & Editing Certifications: edit/edit-certs.md
          - Adding, Editing & Deleting History: edit/edit-history.md
          - Utilities:
              - Flagged Persons: edit/flagged-persons.md
  - Permissions & Access: permissions.md
  - Code: code.md
  - Release Notes: release-notes.md

copyright: Copyright &copy; 2025 Endurance Coalition

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://google.com
      name: Discord
