site_name: EnduraNet Documentation
site_url: https://enduranet.edcgaming.org/docs/
use_directory_urls: true

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
  icon:
    repo: fontawesome/brands/github
  logo: assets/enduranet_logo.png
  favicon: assets/enduranet_logo.ico
  features:
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - toc.integrate
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.tooltips

extra_css:
  - assets/custom.css

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - tables
  - abbr
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md

nav:
  - Welcome: index.md
  - How-Tos:
      - Navigation: how-to/site-nav.md
      - Check Certification Status: how-to/check-cert-status.md
      - Change Permissions: how-to/change-perms.md
      - Logging In: how-to/login.md
      - Member Management:
          - Add a New Member: how-to/add-new-member.md
          - Edit a Member: how-to/edit-member.md
          - Search for a Member: how-to/search-for-member.md
          - Getting Discord and Steam ID: how-to/get-ids.md
      - Certification Management:
          - Add a New Certification: how-to/add-new-cert.md
          - Edit a Certification: how-to/edit-cert.md
          - Search for a Certification: how-to/search-for-cert.md
      - Certification History Management:
          - Add a New Certification Event: how-to/add-new-history.md
          - Edit a Certification Event: how-to/edit-history.md
          - Delete a Certification Event: how-to/delete-history.md
          - Searching for Certification History: how-to/search-history.md
  - Guides:
      - Permissions: guides/permissions.md
      - Flagged Persons: guides/flagged-persons.md
      - Business Logic: guides/business-logic.md
  - Release Notes: release-notes.md
  - Road Map: roadmap.md

copyright: Copyright &copy; 2025 Endurance Coalition

watch:
  - includes

extra:
  generator: true
